# Generated by Django 3.2.9 on 2022-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
    ]
