# Generated by Django 3.2.9 on 2023-04-05 09:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='adress',
            field=models.CharField(default='%Y-%m-%d %H:%M:%S %Z', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Комментарии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='file1',
            field=models.ImageField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='file2',
            field=models.ImageField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='file3',
            field=models.ImageField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='file4',
            field=models.ImageField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='file5',
            field=models.ImageField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='file6',
            field=models.ImageField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='first_name',
            field=models.CharField(default='2011-09-01T13:20:30+03:00', max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='last_name',
            field=models.CharField(default='2011-09-01T13:20:30+03:00', max_length=200, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(default='2011-09-01T13:20:30+03:00', max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид изделия'),
        ),
    ]
