# Generated by Django 3.2.9 on 2023-04-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230405_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.CharField(max_length=99999, verbose_name='Коментарии'),
        ),
    ]
