# Generated by Django 3.2.9 on 2023-04-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_product_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.TextField(max_length=99999, verbose_name='Коментарии'),
        ),
    ]
