# Generated by Django 3.2.9 on 2023-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_product_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file6',
            field=models.FileField(blank=True, null=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
    ]
