# Generated by Django 3.2.9 on 2023-04-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20230410_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adress',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Номер телефона'),
        ),
    ]
