# Generated by Django 3.2.9 on 2022-06-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
